apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup-workspace
spec:
  description: Cleans up the workspace by removing all files and directories.
  workspaces:
    - name: source
  steps:
    - name: cleanup
      image: alpine:3
      workingDir: $(workspaces.source.path)
      securityContext:
        runAsUser: 0
      script: |
        #!/bin/sh
        set -eu
        echo "Cleaning workspace at $(workspaces.source.path)..."

        if [ -d "$(workspaces.source.path)" ]; then
          rm -rf "$(workspaces.source.path:?)"/*
          rm -rf "$(workspaces.source.path)"/.[!.]* || true
          rm -rf "$(workspaces.source.path)"/..?* || true
        fi    
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: eslint
spec:
  workspaces:
    - name: source
  params:
    - name: args
      description: Arguments to pass to ESLint
      type: string
      default: "src/ tests/ --ext *.js"
  steps:
    - name: lint
      image: node:20-alpine
      workingDir: $(workspaces.source.path)
      script: |
        #!/bin/sh
        set -e
        echo "Installing dependencies..."
        npm ci
        echo "Running ESLint..."
        npm run lint $(params.args)